DROP TABLE Machines CASCADE CONSTRAINTS;
DROP TABLE Machine_Maintenance CASCADE CONSTRAINTS;
DROP TABLE Raw_Materials CASCADE CONSTRAINTS;
DROP TABLE Warehouses CASCADE CONSTRAINTS;
DROP TABLE Production_Orders CASCADE CONSTRAINTS;
DROP TABLE Tools CASCADE CONSTRAINTS;
