CREATE TABLE Tools (
  Tool_ID INT NOT NULL,
  Tool_Name varchar2(100) NOT NULL,
  Manufacture_Date DATE NOT NULL,
  Status varchar2(100) NOT NULL,
  PRIMARY KEY (Tool_ID)
);

INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (1, 'Torque Wrench', TO_DATE('2022-04-26', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (2, 'Digital Caliper', TO_DATE('2023-12-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (3, 'Micrometer', TO_DATE('2020-12-27', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (4, 'Laser Level', TO_DATE('2005-07-04', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (5, 'Dial Indicator', TO_DATE('2006-09-04', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (6, 'Feeler Gauge', TO_DATE('2010-08-24', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (7, 'Protractor', TO_DATE('2018-06-19', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (8, 'Angle Finder', TO_DATE('2002-03-05', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (9, 'Ball Hammer', TO_DATE('2016-07-21', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (10, 'Brass Hammer', TO_DATE('2013-09-02', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (11, 'Dead Hammer', TO_DATE('2000-12-14', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (12, 'Chisels', TO_DATE('2012-11-12', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (13, 'Punches', TO_DATE('2009-05-26', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (14, 'Files', TO_DATE('2012-11-08', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (15, 'Deburring Tool', TO_DATE('2014-11-10', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (16, 'Countersink Cutter', TO_DATE('2007-08-06', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (17, 'Drill Bits', TO_DATE('2000-08-13', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (18, 'Reamers', TO_DATE('2012-02-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (19, 'Taps', TO_DATE('2017-09-15', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (20, 'Tap Wrench', TO_DATE('2012-03-13', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (21, 'Die Holder', TO_DATE('2021-02-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (22, 'Hex Keys', TO_DATE('2017-07-16', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (23, 'Spline Keys', TO_DATE('2009-06-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (24, 'Torque Screwdriver', TO_DATE('2008-01-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (25, 'Precision Screwdriver', TO_DATE('2016-07-11', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (26, 'Soldering Iron', TO_DATE('2016-08-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (27, 'Heat Gun', TO_DATE('2022-08-11', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (28, 'Wire Strippers', TO_DATE('2008-03-28', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (29, 'Crimping Tool', TO_DATE('2018-10-25', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (30, 'Cable Cutters', TO_DATE('2014-09-21', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (31, 'Multimeter', TO_DATE('2022-09-07', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (32, 'Oscilloscope', TO_DATE('2006-01-06', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (33, 'Power Supply', TO_DATE('2011-05-15', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (34, 'Bench Magnifier', TO_DATE('2003-06-17', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (35, 'ESD Mat', TO_DATE('2020-10-13', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (36, 'ESD Strap', TO_DATE('2000-02-21', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (37, 'Hardness Tester', TO_DATE('2014-09-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (38, 'Thickness Gauge', TO_DATE('2007-12-08', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (39, 'Vibration Meter', TO_DATE('2022-04-03', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (40, 'Sound Meter', TO_DATE('2016-09-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (41, 'Thermal Imager', TO_DATE('2013-06-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (42, 'Infrared Thermometer', TO_DATE('2007-04-05', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (43, 'Flow Meter', TO_DATE('2021-05-13', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (44, 'Pressure Gauge', TO_DATE('2004-05-28', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (45, 'Vacuum Gauge', TO_DATE('2004-10-07', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (46, 'Leak Detector', TO_DATE('2016-12-27', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (47, 'Force Gauge', TO_DATE('2000-01-06', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (48, 'Tensile Tester', TO_DATE('2001-07-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (49, 'Impact Tester', TO_DATE('2009-02-05', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (50, 'Fatigue Tester', TO_DATE('2012-08-15', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (51, 'Thermocouple', TO_DATE('2007-04-26', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (52, 'RTD Sensor', TO_DATE('2000-04-15', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (53, 'Data Logger', TO_DATE('2008-10-23', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (54, 'Chart Recorder', TO_DATE('2014-08-08', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (55, 'Temperature Controller', TO_DATE('2003-04-19', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (56, 'Humidity Controller', TO_DATE('2015-09-22', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (57, 'PLC', TO_DATE('2021-03-25', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (58, 'HMI', TO_DATE('2009-07-31', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (59, 'Robot Arm', TO_DATE('2008-03-01', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (60, 'CNC Machine', TO_DATE('2014-09-10', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (61, '3D Printer', TO_DATE('2021-04-09', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (62, 'Laser Cutter', TO_DATE('2001-11-25', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (63, 'Plasma Cutter', TO_DATE('2006-09-12', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (64, 'CNC Lathe', TO_DATE('2006-03-21', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (65, 'CNC Router', TO_DATE('2003-03-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (66, 'Welding Machine', TO_DATE('2010-07-28', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (67, 'Laser Welder', TO_DATE('2007-11-30', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (68, 'Spot Welder', TO_DATE('2016-04-22', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (69, 'TIG Welder', TO_DATE('2010-04-29', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (70, 'MIG Welder', TO_DATE('2007-07-23', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (71, 'Arc Welder', TO_DATE('2013-06-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (72, 'Oxy Torch', TO_DATE('2015-04-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (73, 'Soldering Station', TO_DATE('2000-08-21', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (74, 'Fume Extractor', TO_DATE('2015-01-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (75, 'Handheld Grinder', TO_DATE('2000-10-09', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (76, 'Bench Grinder', TO_DATE('2003-08-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (77, 'Belt Sander', TO_DATE('2022-03-06', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (78, 'Disc Sander', TO_DATE('2006-11-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (79, 'Orbital Sander', TO_DATE('2021-01-10', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (80, 'Detail Sander', TO_DATE('2003-05-09', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (81, 'Jigsaw', TO_DATE('2011-06-28', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (82, 'Bandsaw', TO_DATE('2008-08-01', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (83, 'Circular Saw', TO_DATE('2018-01-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (84, 'Table Saw', TO_DATE('2022-10-08', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (85, 'Miter Saw', TO_DATE('2003-01-19', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (86, 'Scroll Saw', TO_DATE('2006-05-13', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (87, 'Track Saw', TO_DATE('2006-07-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (88, 'Chainsaw', TO_DATE('2001-10-27', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (89, 'Tile Saw', TO_DATE('2002-10-29', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (90, 'Wet Saw', TO_DATE('2006-08-27', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (91, 'Concrete Saw', TO_DATE('2010-05-09', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (92, 'Angle Grinder', TO_DATE('2006-09-30', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (93, 'Rotary Tool', TO_DATE('2001-07-10', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (94, 'Impact Driver', TO_DATE('2002-04-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (95, 'Cordless Drill', TO_DATE('2008-10-18', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (96, 'Hammer Drill', TO_DATE('2012-10-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (97, 'Magnetic Drill', TO_DATE('2020-06-25', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (98, 'Air Compressor', TO_DATE('2021-02-15', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (99, 'Air Hose', TO_DATE('2006-05-19', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (100, 'Air Tool', TO_DATE('2017-01-30', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (101, 'Air Ratchet', TO_DATE('2000-05-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (102, 'Air Hammer', TO_DATE('2013-10-30', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (103, 'Air Drill', TO_DATE('2001-12-22', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (104, 'Air Grinder', TO_DATE('2014-11-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (105, 'Air Sander', TO_DATE('2013-02-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (106, 'Air Polisher', TO_DATE('2017-02-08', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (107, 'Hydraulic Jack', TO_DATE('2020-03-31', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (108, 'Bottle Jack', TO_DATE('2008-01-09', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (109, 'Floor Jack', TO_DATE('2001-12-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (110, 'Engine Crane', TO_DATE('2010-04-03', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (111, 'Engine Stand', TO_DATE('2020-05-22', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (112, 'Jack Stand', TO_DATE('2014-12-25', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (113, 'Creeper', TO_DATE('2014-05-16', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (114, 'Mechanics Stool', TO_DATE('2022-01-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (115, 'Tire Inflator', TO_DATE('2001-04-28', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (116, 'Tire Changer', TO_DATE('2018-09-07', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (117, 'Wheel Balancer', TO_DATE('2004-12-26', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (118, 'Brake Lathe', TO_DATE('2008-02-29', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (119, 'Brake Bleeder', TO_DATE('2019-07-29', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (120, 'Oil Pan', TO_DATE('2010-03-19', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (121, 'Oil Wrench', TO_DATE('2014-01-06', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (122, 'Grease Gun', TO_DATE('2006-09-18', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (123, 'Parts Washer', TO_DATE('2021-05-18', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (124, 'Parts Cleaner', TO_DATE('2011-02-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (125, 'Tool Box', TO_DATE('2004-08-16', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (126, 'Tool Chest', TO_DATE('2012-08-22', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (127, 'Tool Cabinet', TO_DATE('2016-11-19', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (128, 'Tool Cart', TO_DATE('2009-06-18', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (129, 'Tool Belt', TO_DATE('2000-07-09', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (130, 'Tool Bag', TO_DATE('2009-09-08', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (131, 'Tool Vest', TO_DATE('2004-07-24', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (132, 'Tool Pouch', TO_DATE('2003-10-10', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (133, 'Workbench', TO_DATE('2006-09-09', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (134, 'Bench Vise', TO_DATE('2008-11-06', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (135, 'Pipe Vise', TO_DATE('2016-11-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (136, 'Sawhorse', TO_DATE('2004-03-27', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (137, 'Step Stool', TO_DATE('2010-02-16', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (138, 'Ladder', TO_DATE('2007-10-01', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (139, 'Scaffolding', TO_DATE('2009-10-17', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (140, 'Scissor Lift', TO_DATE('2005-06-14', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (141, 'Boom Lift', TO_DATE('2019-07-29', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (142, 'Forklift', TO_DATE('2017-06-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (143, 'Pallet Jack', TO_DATE('2013-11-14', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (144, 'Hand Truck', TO_DATE('2006-04-03', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (145, 'Dolly', TO_DATE('2005-01-04', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (146, 'Conveyor', TO_DATE('2009-01-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (147, 'Chain Hoist', TO_DATE('2023-06-26', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (148, 'Lever Hoist', TO_DATE('2005-10-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (149, 'Electric Hoist', TO_DATE('2004-11-04', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (150, 'Winch', TO_DATE('2009-10-22', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (151, 'Crane', TO_DATE('2006-01-31', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (152, 'Rigging', TO_DATE('2003-04-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (153, 'Slings', TO_DATE('2015-10-30', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (154, 'Shackles', TO_DATE('2017-07-07', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (155, 'Hooks', TO_DATE('2012-05-06', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (156, 'Ratchet Strap', TO_DATE('2008-08-25', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (157, 'Load Binder', TO_DATE('2016-03-31', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (158, 'Cargo Net', TO_DATE('2006-04-02', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (159, 'Cargo Bar', TO_DATE('2013-03-18', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (160, 'Ratchet', TO_DATE('2003-08-06', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (161, 'Socket', TO_DATE('2002-05-31', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (162, 'Extension Bar', TO_DATE('2005-01-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (163, 'Universal Joint', TO_DATE('2004-06-26', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (164, 'Breaker Bar', TO_DATE('2020-07-28', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (165, 'Flex Ratchet', TO_DATE('2006-04-29', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (166, 'Combination Wrench', TO_DATE('2006-03-20', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (167, 'Box Wrench', TO_DATE('2006-04-29', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (168, 'Flare Wrench', TO_DATE('2012-08-19', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (169, 'Crowfoot Wrench', TO_DATE('2002-10-07', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (170, 'Pipe Wrench', TO_DATE('2016-11-27', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (171, 'Allen Wrench', TO_DATE('2011-11-26', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (172, 'Torx Wrench', TO_DATE('2013-09-21', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (173, 'Pliers', TO_DATE('2018-08-05', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (174, 'Cutting Pliers', TO_DATE('2017-07-17', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (175, 'Slip Pliers', TO_DATE('2012-04-01', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (176, 'Locking Pliers', TO_DATE('2014-05-07', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (177, 'Snap Pliers', TO_DATE('2008-09-09', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (178, 'Wire Cutters', TO_DATE('2012-04-01', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (179, 'Bolt Cutters', TO_DATE('2023-07-06', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (180, 'Tin Snips', TO_DATE('2016-09-12', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (181, 'Sheet Shear', TO_DATE('2004-02-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (182, 'Sheet Roller', TO_DATE('2016-03-20', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (183, 'Punch Machine', TO_DATE('2020-07-13', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (184, 'Swaging Machine', TO_DATE('2001-05-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (185, 'Body Hammer', TO_DATE('2022-01-17', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (186, 'Slide Hammer', TO_DATE('2002-01-25', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (187, 'Puller Set', TO_DATE('2016-11-29', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (188, 'Gear Puller', TO_DATE('2013-05-15', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (189, 'Bearing Puller', TO_DATE('2007-02-12', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (190, 'Joint Press', TO_DATE('2001-02-19', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (191, 'Drift Punch', TO_DATE('2023-04-04', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (192, 'Center Punch', TO_DATE('2002-01-26', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (193, 'Pin Punch', TO_DATE('2005-03-09', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (194, 'Punch Set', TO_DATE('2018-08-15', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (195, 'Hex Key', TO_DATE('2015-04-06', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (196, 'Torx Key', TO_DATE('2004-11-12', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (197, 'Screwdriver Set', TO_DATE('2004-03-02', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (198, 'Carbide Burr', TO_DATE('2015-07-31', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (199, 'Router Bit', TO_DATE('2017-12-22', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (200, 'Hole Saw', TO_DATE('2019-02-15', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (201, 'Jigsaw Blade', TO_DATE('2013-05-20', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (202, 'Saw Blade', TO_DATE('2006-12-02', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (203, 'Razor Blade', TO_DATE('2006-04-02', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (204, 'Utility Knife', TO_DATE('2001-01-23', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (205, 'Safety Knife', TO_DATE('2014-09-15', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (206, 'Paint Scraper', TO_DATE('2022-12-30', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (207, 'Chisel Set', TO_DATE('2013-02-20', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (208, 'Wood Chisel', TO_DATE('2000-04-05', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (209, 'Mortise Chisel', TO_DATE('2011-11-15', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (210, 'Cold Chisel', TO_DATE('2001-01-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (211, 'Glass Cutter', TO_DATE('2017-07-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (212, 'Wire Stripper', TO_DATE('2015-11-27', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (213, 'Cable Stripper', TO_DATE('2004-02-19', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (214, 'Tube Cutter', TO_DATE('2010-04-22', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (215, 'Pipe Cutter', TO_DATE('2011-05-09', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (216, 'PVC Cutter', TO_DATE('2004-07-21', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (217, 'Copper Cutter', TO_DATE('2009-10-08', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (218, 'Brake Cutter', TO_DATE('2022-05-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (219, 'Fuel Cutter', TO_DATE('2020-04-29', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (220, 'Hose Cutter', TO_DATE('2014-06-12', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (221, 'Torque Wrench', TO_DATE('2000-09-14', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (222, 'Digital Caliper', TO_DATE('2010-01-23', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (223, 'Micrometer', TO_DATE('2003-03-08', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (224, 'Laser Level', TO_DATE('2016-03-20', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (225, 'Dial Indicator', TO_DATE('2004-07-15', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (226, 'Feeler Gauge', TO_DATE('2008-06-19', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (227, 'Protractor', TO_DATE('2000-04-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (228, 'Angle Finder', TO_DATE('2021-11-30', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (229, 'Ball Hammer', TO_DATE('2010-04-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (230, 'Brass Hammer', TO_DATE('2019-06-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (231, 'Dead Hammer', TO_DATE('2014-02-19', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (232, 'Chisels', TO_DATE('2006-09-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (233, 'Punches', TO_DATE('2021-01-27', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (234, 'Files', TO_DATE('2009-03-28', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (235, 'Deburring Tool', TO_DATE('2010-10-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (236, 'Countersink Cutter', TO_DATE('2016-04-02', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (237, 'Drill Bits', TO_DATE('2007-04-26', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (238, 'Reamers', TO_DATE('2013-10-15', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (239, 'Taps', TO_DATE('2010-06-04', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (240, 'Tap Wrench', TO_DATE('2014-05-13', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (241, 'Die Holder', TO_DATE('2002-05-04', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (242, 'Hex Keys', TO_DATE('2016-06-08', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (243, 'Spline Keys', TO_DATE('2003-03-16', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (244, 'Torque Screwdriver', TO_DATE('2005-03-28', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (245, 'Precision Screwdriver', TO_DATE('2007-06-23', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (246, 'Soldering Iron', TO_DATE('2003-04-13', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (247, 'Heat Gun', TO_DATE('2014-09-03', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (248, 'Wire Strippers', TO_DATE('2004-04-20', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (249, 'Crimping Tool', TO_DATE('2002-01-24', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (250, 'Cable Cutters', TO_DATE('2006-10-27', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (251, 'Multimeter', TO_DATE('2021-08-12', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (252, 'Oscilloscope', TO_DATE('2000-04-04', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (253, 'Power Supply', TO_DATE('2009-11-20', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (254, 'Bench Magnifier', TO_DATE('2000-05-03', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (255, 'ESD Mat', TO_DATE('2008-01-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (256, 'ESD Strap', TO_DATE('2016-11-20', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (257, 'Hardness Tester', TO_DATE('2017-08-14', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (258, 'Thickness Gauge', TO_DATE('2004-12-02', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (259, 'Vibration Meter', TO_DATE('2003-06-18', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (260, 'Sound Meter', TO_DATE('2015-01-25', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (261, 'Thermal Imager', TO_DATE('2017-05-30', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (262, 'Infrared Thermometer', TO_DATE('2012-07-15', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (263, 'Flow Meter', TO_DATE('2006-02-23', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (264, 'Pressure Gauge', TO_DATE('2009-12-25', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (265, 'Vacuum Gauge', TO_DATE('2019-04-07', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (266, 'Leak Detector', TO_DATE('2012-11-04', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (267, 'Force Gauge', TO_DATE('2010-03-31', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (268, 'Tensile Tester', TO_DATE('2008-11-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (269, 'Impact Tester', TO_DATE('2000-12-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (270, 'Fatigue Tester', TO_DATE('2017-10-01', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (271, 'Thermocouple', TO_DATE('2004-02-18', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (272, 'RTD Sensor', TO_DATE('2008-02-29', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (273, 'Data Logger', TO_DATE('2021-01-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (274, 'Chart Recorder', TO_DATE('2019-03-24', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (275, 'Temperature Controller', TO_DATE('2015-05-29', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (276, 'Humidity Controller', TO_DATE('2004-10-07', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (277, 'PLC', TO_DATE('2014-05-02', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (278, 'HMI', TO_DATE('2008-09-24', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (279, 'Robot Arm', TO_DATE('2018-05-10', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (280, 'CNC Machine', TO_DATE('2018-09-21', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (281, '3D Printer', TO_DATE('2007-12-30', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (282, 'Laser Cutter', TO_DATE('2004-01-22', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (283, 'Plasma Cutter', TO_DATE('2004-06-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (284, 'CNC Lathe', TO_DATE('2007-05-05', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (285, 'CNC Router', TO_DATE('2015-05-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (286, 'Welding Machine', TO_DATE('2019-02-18', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (287, 'Laser Welder', TO_DATE('2014-03-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (288, 'Spot Welder', TO_DATE('2002-04-04', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (289, 'TIG Welder', TO_DATE('2013-04-01', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (290, 'MIG Welder', TO_DATE('2010-05-02', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (291, 'Arc Welder', TO_DATE('2014-06-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (292, 'Oxy Torch', TO_DATE('2000-12-04', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (293, 'Soldering Station', TO_DATE('2006-08-07', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (294, 'Fume Extractor', TO_DATE('2016-06-27', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (295, 'Handheld Grinder', TO_DATE('2022-12-12', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (296, 'Bench Grinder', TO_DATE('2015-12-17', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (297, 'Belt Sander', TO_DATE('2009-10-27', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (298, 'Disc Sander', TO_DATE('2011-12-05', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (299, 'Orbital Sander', TO_DATE('2001-08-20', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (300, 'Detail Sander', TO_DATE('2000-04-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (301, 'Jigsaw', TO_DATE('2011-02-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (302, 'Bandsaw', TO_DATE('2004-07-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (303, 'Circular Saw', TO_DATE('2015-03-13', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (304, 'Table Saw', TO_DATE('2023-10-03', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (305, 'Miter Saw', TO_DATE('2014-05-23', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (306, 'Scroll Saw', TO_DATE('2015-03-09', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (307, 'Track Saw', TO_DATE('2020-11-17', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (308, 'Chainsaw', TO_DATE('2000-10-30', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (309, 'Tile Saw', TO_DATE('2014-06-05', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (310, 'Wet Saw', TO_DATE('2007-01-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (311, 'Concrete Saw', TO_DATE('2023-02-16', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (312, 'Angle Grinder', TO_DATE('2013-04-25', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (313, 'Rotary Tool', TO_DATE('2008-11-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (314, 'Impact Driver', TO_DATE('2015-09-13', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (315, 'Cordless Drill', TO_DATE('2014-11-25', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (316, 'Hammer Drill', TO_DATE('2018-02-14', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (317, 'Magnetic Drill', TO_DATE('2013-03-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (318, 'Air Compressor', TO_DATE('2014-12-27', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (319, 'Air Hose', TO_DATE('2009-08-18', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (320, 'Air Tool', TO_DATE('2012-09-05', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (321, 'Air Ratchet', TO_DATE('2010-03-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (322, 'Air Hammer', TO_DATE('2004-12-22', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (323, 'Air Drill', TO_DATE('2000-11-06', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (324, 'Air Grinder', TO_DATE('2012-05-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (325, 'Air Sander', TO_DATE('2011-12-17', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (326, 'Air Polisher', TO_DATE('2017-05-31', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (327, 'Hydraulic Jack', TO_DATE('2003-11-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (328, 'Bottle Jack', TO_DATE('2011-08-02', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (329, 'Floor Jack', TO_DATE('2018-09-25', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (330, 'Engine Crane', TO_DATE('2004-08-04', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (331, 'Engine Stand', TO_DATE('2011-10-19', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (332, 'Jack Stand', TO_DATE('2022-09-13', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (333, 'Creeper', TO_DATE('2003-08-16', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (334, 'Mechanics Stool', TO_DATE('2012-08-23', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (335, 'Tire Inflator', TO_DATE('2023-05-30', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (336, 'Tire Changer', TO_DATE('2000-04-14', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (337, 'Wheel Balancer', TO_DATE('2019-12-22', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (338, 'Brake Lathe', TO_DATE('2012-03-20', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (339, 'Brake Bleeder', TO_DATE('2009-12-03', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (340, 'Oil Pan', TO_DATE('2009-06-09', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (341, 'Oil Wrench', TO_DATE('2014-12-23', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (342, 'Grease Gun', TO_DATE('2009-05-19', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (343, 'Parts Washer', TO_DATE('2006-11-11', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (344, 'Parts Cleaner', TO_DATE('2002-09-18', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (345, 'Tool Box', TO_DATE('2014-12-31', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (346, 'Tool Chest', TO_DATE('2009-01-12', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (347, 'Tool Cabinet', TO_DATE('2005-12-31', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (348, 'Tool Cart', TO_DATE('2020-01-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (349, 'Tool Belt', TO_DATE('2002-06-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (350, 'Tool Bag', TO_DATE('2010-12-28', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (351, 'Tool Vest', TO_DATE('2012-11-10', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (352, 'Tool Pouch', TO_DATE('2023-12-31', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (353, 'Workbench', TO_DATE('2004-02-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (354, 'Bench Vise', TO_DATE('2012-08-24', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (355, 'Pipe Vise', TO_DATE('2007-12-05', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (356, 'Sawhorse', TO_DATE('2014-10-29', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (357, 'Step Stool', TO_DATE('2011-08-03', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (358, 'Ladder', TO_DATE('2006-04-30', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (359, 'Scaffolding', TO_DATE('2001-10-21', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (360, 'Scissor Lift', TO_DATE('2001-01-23', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (361, 'Boom Lift', TO_DATE('2006-12-29', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (362, 'Forklift', TO_DATE('2023-03-01', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (363, 'Pallet Jack', TO_DATE('2007-06-21', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (364, 'Hand Truck', TO_DATE('2021-03-04', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (365, 'Dolly', TO_DATE('2019-04-16', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (366, 'Conveyor', TO_DATE('2018-11-14', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (367, 'Chain Hoist', TO_DATE('2019-01-15', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (368, 'Lever Hoist', TO_DATE('2008-10-11', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (369, 'Electric Hoist', TO_DATE('2015-07-04', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (370, 'Winch', TO_DATE('2004-09-23', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (371, 'Crane', TO_DATE('2014-12-16', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (372, 'Rigging', TO_DATE('2015-10-30', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (373, 'Slings', TO_DATE('2018-05-04', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (374, 'Shackles', TO_DATE('2010-02-07', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (375, 'Hooks', TO_DATE('2003-03-10', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (376, 'Ratchet Strap', TO_DATE('2010-09-14', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (377, 'Load Binder', TO_DATE('2010-08-11', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (378, 'Cargo Net', TO_DATE('2001-09-22', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (379, 'Cargo Bar', TO_DATE('2009-05-12', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (380, 'Ratchet', TO_DATE('2007-08-15', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (381, 'Socket', TO_DATE('2010-09-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (382, 'Extension Bar', TO_DATE('2001-12-28', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (383, 'Universal Joint', TO_DATE('2002-03-28', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (384, 'Breaker Bar', TO_DATE('2023-10-26', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (385, 'Flex Ratchet', TO_DATE('2005-10-13', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (386, 'Combination Wrench', TO_DATE('2009-10-19', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (387, 'Box Wrench', TO_DATE('2018-06-22', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (388, 'Flare Wrench', TO_DATE('2007-07-07', 'YYYY-MM-DD'), 'In Use');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (389, 'Crowfoot Wrench', TO_DATE('2005-07-29', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (390, 'Pipe Wrench', TO_DATE('2021-05-14', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (391, 'Allen Wrench', TO_DATE('2011-04-01', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (392, 'Torx Wrench', TO_DATE('2016-11-25', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (393, 'Pliers', TO_DATE('2012-07-16', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (394, 'Cutting Pliers', TO_DATE('2008-08-28', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (395, 'Slip Pliers', TO_DATE('2004-05-05', 'YYYY-MM-DD'), 'Maintenance');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (396, 'Locking Pliers', TO_DATE('2008-03-12', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (397, 'Snap Pliers', TO_DATE('2008-06-23', 'YYYY-MM-DD'), 'Available');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (398, 'Wire Cutters', TO_DATE('2004-11-27', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (399, 'Bolt Cutters', TO_DATE('2006-11-06', 'YYYY-MM-DD'), 'Retired');
INSERT INTO Tools (Tool_ID, Tool_Name, Manufacture_Date, Status) VALUES (400, 'Tin Snips', TO_DATE('2006-05-27', 'YYYY-MM-DD'), 'Maintenance');
