create table Warehouses (
	Warehouse_ID INT,
	Warehouse_Location VARCHAR(16),
	Capacity INT,
	Current_Quantity INT
);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (1, 'Irvine', 9275, 6066);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (2, 'Tulsa', 9044, 6457);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (3, 'Fremont', 9651, 5931);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (4, 'Chula Vista', 9491, 6232);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (5, 'Wichita', 9795, 6110);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (6, 'Anaheim', 9135, 6588);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (7, 'Garland', 9927, 7335);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (8, 'Louisville', 9476, 5528);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (9, 'Stockton', 9089, 6896);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (10, 'Lexington', 9284, 6199);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (11, 'Fresno', 9988, 7581);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (12, 'Corpus Christi', 9044, 7546);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (13, 'Milwaukee', 9323, 8257);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (14, 'Reno', 9668, 6448);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (15, 'Portland', 9055, 8842);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (16, 'Chesapeake', 9128, 8049);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (17, 'Toledo', 9169, 8268);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (18, 'Hialeah', 9557, 8986);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (19, 'Cleveland', 9281, 5757);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (20, 'Hialeah', 9503, 6294);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (21, 'Aurora', 9854, 7536);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (22, 'Seattle', 9840, 8348);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (23, 'Anaheim', 9576, 8598);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (24, 'Plano', 9344, 6740);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (25, 'Scottsdale', 9923, 5270);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (26, 'Tucson', 9916, 8996);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (27, 'Seattle', 9620, 7319);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (28, 'Toledo', 9046, 8937);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (29, 'North Las Vegas', 9674, 8314);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (30, 'Charlotte', 9163, 7221);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (31, 'Lincoln', 9193, 6543);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (32, 'Boston', 9579, 7145);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (33, 'Louisville', 9219, 5313);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (34, 'Washington', 9816, 7927);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (35, 'Miami', 9606, 7657);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (36, 'Mesa', 9470, 5046);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (37, 'Buffalo', 9424, 6182);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (38, 'Philadelphia', 9005, 6790);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (39, 'Lexington', 9817, 5047);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (40, 'Jersey City', 9904, 5908);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (41, 'Lubbock', 9090, 6126);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (42, 'Plano', 9442, 8204);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (43, 'Phoenix', 9924, 8395);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (44, 'Miami', 9779, 8980);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (45, 'Sacramento', 9696, 5527);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (46, 'Winston-Salem', 9519, 8650);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (47, 'Omaha', 9700, 7865);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (48, 'New Orleans', 9294, 8535);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (49, 'Chicago', 9871, 5106);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (50, 'Madison', 9644, 5991);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (51, 'Louisville', 9439, 5515);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (52, 'North Las Vegas', 9394, 8506);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (53, 'Phoenix', 9112, 5525);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (54, 'Cincinnati', 9273, 5671);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (55, 'Atlanta', 9368, 6564);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (56, 'Honolulu', 9213, 5756);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (57, 'Kansas City', 9997, 7456);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (58, 'Riverside', 9160, 6237);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (59, 'Jacksonville', 9223, 6700);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (60, 'Austin', 9044, 8830);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (61, 'San Jose', 9481, 7173);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (62, 'Reno', 9299, 8507);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (63, 'Milwaukee', 9989, 5714);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (64, 'Cincinnati', 9021, 7430);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (65, 'Lincoln', 9853, 8856);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (66, 'Houston', 9074, 7921);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (67, 'Columbus', 9098, 8710);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (68, 'Newark', 9546, 6687);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (69, 'Oklahoma City', 9292, 6769);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (70, 'Virginia Beach', 9366, 6265);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (71, 'Indianapolis', 9652, 7990);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (72, 'Dallas', 9395, 8039);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (73, 'Toledo', 9415, 6780);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (74, 'Dallas', 9256, 8322);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (75, 'Jacksonville', 9359, 6047);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (76, 'Arlington', 9451, 7881);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (77, 'Cleveland', 9447, 8062);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (78, 'Sacramento', 9268, 6103);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (79, 'Phoenix', 9926, 6045);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (80, 'Fremont', 9813, 5325);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (81, 'Houston', 9180, 5271);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (82, 'Philadelphia', 9897, 6796);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (83, 'Fresno', 9532, 7020);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (84, 'Scottsdale', 9742, 5611);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (85, 'St. Petersburg', 9715, 7698);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (86, 'Miami', 9652, 7571);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (87, 'New York', 9287, 5100);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (88, 'Fresno', 9003, 7357);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (89, 'Durham', 9944, 8883);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (90, 'San Diego', 9268, 5477);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (91, 'New York', 9134, 5121);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (92, 'Chandler', 9194, 8097);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (93, 'Tulsa', 9392, 6843);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (94, 'Fort Wayne', 9404, 5681);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (95, 'Nashville', 9660, 8976);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (96, 'Gilbert', 9190, 6693);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (97, 'Irvine', 9850, 5500);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (98, 'Pittsburgh', 9205, 7783);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (99, 'Mesa', 9297, 7795);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (100, 'Arlington', 9887, 7098);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (101, 'Long Beach', 9229, 8579);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (102, 'Reno', 9376, 8953);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (103, 'Detroit', 9230, 6880);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (104, 'Long Beach', 9525, 7419);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (105, 'Sacramento', 9225, 5068);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (106, 'Portland', 9791, 5560);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (107, 'Baltimore', 9873, 8707);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (108, 'Austin', 9631, 6422);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (109, 'Hialeah', 9805, 5470);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (110, 'Madison', 9143, 6077);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (111, 'Tulsa', 9161, 6331);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (112, 'Lincoln', 9965, 6759);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (113, 'Boise', 9557, 7387);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (114, 'Philadelphia', 9390, 8994);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (115, 'Oklahoma City', 9870, 8369);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (116, 'San Antonio', 9338, 8290);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (117, 'Aurora', 9045, 7380);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (118, 'Tulsa', 9589, 5285);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (119, 'Cincinnati', 9908, 8822);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (120, 'Houston', 9831, 7315);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (121, 'Lincoln', 9791, 6767);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (122, 'Chesapeake', 9592, 8243);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (123, 'Chula Vista', 9385, 6758);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (124, 'Dallas', 9776, 8937);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (125, 'Louisville', 9780, 8687);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (126, 'Omaha', 9329, 7893);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (127, 'Dallas', 9486, 6814);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (128, 'Philadelphia', 9851, 8901);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (129, 'Albuquerque', 9144, 7410);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (130, 'Fort Wayne', 9201, 8870);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (131, 'Los Angeles', 9126, 6239);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (132, 'Detroit', 9978, 6310);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (133, 'Indianapolis', 9404, 5620);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (134, 'Las Vegas', 9051, 6890);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (135, 'Irving', 9421, 8710);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (136, 'San Jose', 9567, 7090);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (137, 'Denver', 9384, 7998);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (138, 'Detroit', 9834, 8437);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (139, 'Washington', 9929, 6494);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (140, 'Honolulu', 9207, 5016);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (141, 'Tulsa', 9486, 8676);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (142, 'Denver', 9980, 5298);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (143, 'Lexington', 9530, 6347);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (144, 'Winston-Salem', 9341, 8459);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (145, 'Dallas', 9047, 7458);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (146, 'San Francisco', 9589, 8045);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (147, 'Washington', 9168, 6019);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (148, 'Boise', 9754, 6557);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (149, 'Virginia Beach', 9928, 6246);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (150, 'Fresno', 9557, 5426);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (151, 'Oakland', 9233, 7422);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (152, 'Mesa', 9765, 7535);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (153, 'Phoenix', 9085, 6576);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (154, 'San Francisco', 9218, 7239);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (155, 'Irvine', 9554, 6384);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (156, 'Irving', 9067, 5180);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (157, 'Aurora', 9277, 5518);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (158, 'Raleigh', 9366, 5468);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (159, 'Bakersfield', 9759, 8592);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (160, 'Gilbert', 9851, 5450);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (161, 'Milwaukee', 9445, 8551);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (162, 'Phoenix', 9882, 8196);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (163, 'Miami', 9660, 7699);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (164, 'Jacksonville', 9222, 5639);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (165, 'Lexington', 9698, 6468);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (166, 'Louisville', 9914, 7691);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (167, 'Glendale', 9323, 8169);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (168, 'Tucson', 9671, 6805);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (169, 'Lincoln', 9135, 5673);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (170, 'Jersey City', 9937, 6911);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (171, 'Seattle', 9751, 8462);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (172, 'Chesapeake', 9809, 7719);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (173, 'Anchorage', 9274, 5099);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (174, 'Aurora', 10000, 8331);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (175, 'Phoenix', 9576, 6000);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (176, 'Glendale', 9608, 5922);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (177, 'Fort Wayne', 9674, 8332);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (178, 'Newark', 9142, 8182);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (179, 'Albuquerque', 9440, 6575);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (180, 'Santa Ana', 9656, 8365);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (181, 'Honolulu', 9442, 8139);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (182, 'Mesa', 9742, 7367);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (183, 'St. Petersburg', 9034, 8500);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (184, 'Scottsdale', 9412, 7976);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (185, 'Tulsa', 9817, 8898);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (186, 'Arlington', 9965, 8739);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (187, 'Stockton', 9788, 5875);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (188, 'Tulsa', 9073, 7487);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (189, 'New York', 9309, 7087);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (190, 'Durham', 9265, 8510);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (191, 'San Francisco', 9349, 8447);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (192, 'Tucson', 9577, 6634);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (193, 'Portland', 9074, 5438);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (194, 'Reno', 9469, 6574);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (195, 'Tucson', 9115, 7615);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (196, 'Gilbert', 9715, 5061);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (197, 'Jacksonville', 9552, 6949);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (198, 'Bakersfield', 9943, 6179);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (199, 'Winston-Salem', 9865, 5292);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (200, 'Lubbock', 9037, 7227);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (201, 'Columbus', 9544, 6052);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (202, 'Chicago', 9628, 6279);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (203, 'Baltimore', 9479, 8000);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (204, 'Columbus', 9925, 8058);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (205, 'San Antonio', 9611, 7712);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (206, 'Riverside', 9492, 5917);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (207, 'Hialeah', 9140, 5527);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (208, 'Seattle', 9601, 6171);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (209, 'Columbus', 9975, 8490);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (210, 'Arlington', 9108, 5278);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (211, 'Kansas City', 9300, 6029);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (212, 'Chesapeake', 9950, 6316);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (213, 'Buffalo', 9461, 8763);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (214, 'Laredo', 9312, 7115);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (215, 'Fremont', 9753, 8376);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (216, 'Garland', 9623, 5715);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (217, 'Houston', 9850, 8138);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (218, 'Irving', 9327, 6426);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (219, 'Aurora', 9054, 6578);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (220, 'Greensboro', 9431, 8847);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (221, 'Riverside', 9186, 6840);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (222, 'Colorado Springs', 9539, 8004);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (223, 'Durham', 9227, 5155);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (224, 'Madison', 9784, 7725);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (225, 'Memphis', 9206, 8640);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (226, 'Fort Wayne', 9792, 5770);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (227, 'Pittsburgh', 9532, 7720);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (228, 'Stockton', 9679, 8633);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (229, 'Plano', 9924, 8009);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (230, 'Orlando', 9779, 7677);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (231, 'Virginia Beach', 9471, 8592);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (232, 'Colorado Springs', 9380, 8218);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (233, 'El Paso', 9266, 5772);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (234, 'Denver', 9949, 5550);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (235, 'Jacksonville', 9107, 7295);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (236, 'Raleigh', 9131, 8500);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (237, 'Mesa', 9768, 6782);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (238, 'Kansas City', 9453, 8546);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (239, 'Jersey City', 9822, 5500);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (240, 'Virginia Beach', 9924, 6993);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (241, 'Virginia Beach', 9456, 8489);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (242, 'El Paso', 9562, 5838);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (243, 'New Orleans', 9210, 6113);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (244, 'New Orleans', 9073, 6433);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (245, 'Pittsburgh', 9022, 6018);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (246, 'Anchorage', 9499, 7562);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (247, 'Bakersfield', 9342, 5345);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (248, 'Fort Worth', 9741, 5316);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (249, 'San Francisco', 9577, 8968);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (250, 'St. Louis', 9014, 5088);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (251, 'Tampa', 9371, 5022);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (252, 'Detroit', 9069, 7998);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (253, 'Lincoln', 9569, 5652);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (254, 'Santa Ana', 9998, 5769);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (255, 'Lincoln', 9930, 7442);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (256, 'St. Petersburg', 9283, 8437);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (257, 'Reno', 9867, 7826);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (258, 'San Antonio', 9586, 7379);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (259, 'Bakersfield', 9261, 8997);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (260, 'Chesapeake', 9854, 5417);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (261, 'Cleveland', 9132, 5244);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (262, 'Arlington', 9586, 7107);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (263, 'Fresno', 9010, 6200);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (264, 'Newark', 9095, 6116);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (265, 'Fort Worth', 9185, 5738);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (266, 'Aurora', 9770, 8236);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (267, 'Riverside', 9164, 8693);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (268, 'Memphis', 9773, 8844);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (269, 'Pittsburgh', 9216, 8649);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (270, 'Hialeah', 9011, 8734);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (271, 'Jacksonville', 9757, 7828);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (272, 'Pittsburgh', 9185, 7989);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (273, 'Chula Vista', 9612, 5494);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (274, 'Santa Ana', 9441, 8340);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (275, 'Lexington', 9050, 8731);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (276, 'Norfolk', 9882, 6308);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (277, 'Lubbock', 9858, 6043);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (278, 'Henderson', 9949, 7275);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (279, 'Chicago', 9979, 5938);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (280, 'Virginia Beach', 9472, 5421);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (281, 'Omaha', 9316, 5705);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (282, 'Winston-Salem', 9921, 6334);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (283, 'Santa Ana', 9916, 5222);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (284, 'Charlotte', 9085, 6000);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (285, 'Charlotte', 9262, 8515);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (286, 'Gilbert', 9296, 7882);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (287, 'North Las Vegas', 9457, 5250);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (288, 'Nashville', 9767, 8072);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (289, 'Honolulu', 9142, 6577);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (290, 'St. Petersburg', 9352, 5119);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (291, 'Seattle', 9397, 9000);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (292, 'Tulsa', 9761, 5473);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (293, 'Portland', 9923, 6526);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (294, 'New Orleans', 9916, 6740);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (295, 'Henderson', 9225, 5110);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (296, 'Minneapolis', 9974, 8715);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (297, 'Garland', 9480, 5305);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (298, 'Gilbert', 9742, 8540);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (299, 'Fresno', 9790, 8670);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (300, 'San Jose', 9861, 6852);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (301, 'Greensboro', 9516, 8608);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (302, 'Chicago', 9776, 7515);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (303, 'Colorado Springs', 9399, 6042);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (304, 'Minneapolis', 9041, 7984);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (305, 'Lincoln', 9060, 5859);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (306, 'Long Beach', 9462, 7111);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (307, 'Seattle', 9452, 5068);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (308, 'St. Petersburg', 9767, 6492);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (309, 'Virginia Beach', 9963, 6508);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (310, 'Phoenix', 9669, 5047);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (311, 'Newark', 9575, 6920);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (312, 'Arlington', 9744, 5820);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (313, 'Stockton', 9485, 8192);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (314, 'Wichita', 9942, 7143);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (315, 'Indianapolis', 9993, 7811);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (316, 'Houston', 9701, 6368);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (317, 'Washington', 9277, 5634);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (318, 'Wichita', 9549, 6536);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (319, 'Boise', 9967, 5407);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (320, 'Albuquerque', 9357, 6189);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (321, 'Lubbock', 9935, 8413);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (322, 'Newark', 9212, 7382);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (323, 'Tampa', 9664, 5088);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (324, 'Chandler', 9822, 8768);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (325, 'Bakersfield', 9278, 6868);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (326, 'Aurora', 9797, 5046);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (327, 'Jacksonville', 9104, 7989);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (328, 'Charlotte', 9929, 8300);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (329, 'Lincoln', 9970, 7472);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (330, 'Colorado Springs', 9040, 8165);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (331, 'Milwaukee', 9235, 6536);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (332, 'Santa Ana', 9357, 7487);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (333, 'Fremont', 9356, 5803);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (334, 'Lexington', 9459, 6072);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (335, 'Stockton', 9105, 8815);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (336, 'Glendale', 9816, 8707);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (337, 'Arlington', 9053, 5661);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (338, 'North Las Vegas', 9401, 6448);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (339, 'Portland', 9494, 5301);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (340, 'Mesa', 9818, 8669);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (341, 'Baltimore', 9509, 7788);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (342, 'Bakersfield', 9951, 6980);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (343, 'Houston', 9762, 7675);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (344, 'Tucson', 9288, 5387);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (345, 'Sacramento', 9978, 8390);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (346, 'Boston', 9080, 6847);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (347, 'Tulsa', 9651, 5764);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (348, 'New York', 9846, 8792);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (349, 'Louisville', 9857, 7792);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (350, 'Minneapolis', 9750, 5396);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (351, 'Milwaukee', 9939, 8282);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (352, 'Durham', 9592, 8897);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (353, 'Irvine', 9630, 8349);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (354, 'Chandler', 9774, 7584);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (355, 'Detroit', 9789, 8041);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (356, 'Minneapolis', 9077, 5190);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (357, 'Fort Wayne', 9755, 8302);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (358, 'Fort Worth', 9239, 5261);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (359, 'Indianapolis', 9026, 7815);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (360, 'Jersey City', 9419, 6149);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (361, 'Chandler', 9118, 8808);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (362, 'Irvine', 9805, 6941);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (363, 'Memphis', 9808, 7940);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (364, 'Pittsburgh', 9459, 7962);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (365, 'Memphis', 9092, 7183);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (366, 'Scottsdale', 9945, 7568);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (367, 'Cincinnati', 9427, 8249);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (368, 'Bakersfield', 9860, 8809);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (369, 'Houston', 9860, 7166);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (370, 'Milwaukee', 9312, 6808);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (371, 'Boston', 9753, 5319);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (372, 'Norfolk', 9174, 8592);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (373, 'Gilbert', 9977, 6126);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (374, 'Louisville', 9006, 5421);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (375, 'Tulsa', 9184, 6434);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (376, 'Greensboro', 9221, 6048);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (377, 'Garland', 9052, 5971);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (378, 'Los Angeles', 9166, 7989);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (379, 'Irvine', 9920, 7496);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (380, 'Anaheim', 9912, 6513);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (381, 'Anaheim', 9473, 8967);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (382, 'Jacksonville', 9939, 6346);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (383, 'Henderson', 9296, 5490);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (384, 'Omaha', 9977, 5525);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (385, 'Oakland', 9344, 6331);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (386, 'St. Louis', 9564, 7912);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (387, 'Cincinnati', 9289, 8668);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (388, 'San Antonio', 9675, 7626);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (389, 'Cincinnati', 9090, 8085);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (390, 'Chesapeake', 9161, 7055);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (391, 'Honolulu', 9199, 8614);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (392, 'Plano', 9684, 6532);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (393, 'Anaheim', 9284, 5595);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (394, 'Fort Worth', 9251, 5371);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (395, 'Reno', 9985, 6542);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (396, 'Plano', 9380, 8234);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (397, 'Anchorage', 9702, 5972);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (398, 'Henderson', 9319, 7254);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (399, 'Toledo', 9991, 6536);
insert into Warehouses (Warehouse_ID, Warehouse_Location, Capacity, Current_Quantity) values (400, 'Jersey City', 9180, 7111);
